version: 2

run:
  timeout: 5m
  tests: true
  go: '1.25'

linters:
  enable:
    - errcheck
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - goconst
    - gocyclo
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - dupl
    - dupword
    - embeddedstructfieldcheck
    - funlen
    - gosec
    - iface
    - inamedparam
    - lll
    - loggercheck

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  funlen:
    lines: 100
    statements: 50
  lll:
    line-length: 120

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
